export const SET_IS_LOADING = 'SET_IS_LOADING';
export const PRODUCTS_RECEIVED = 'PRODUCTS_RECEIVED'
export const SET_PAGE_SIZE = 'SET_PAGE_SIZE'
export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER'

export const PRODUCT_RECEIVED = 'PRODUCT_RECEIVED'
export const REVIEW_ADDED = 'REVIEW_ADDED'

